import Foundation

/// Distinguishes user-placed markers from generated beat markers (F-15).
public enum MarkerKind: String, Codable, Sendable, Equatable {
    /// A user-created marker with a name and flag.
    case standard

    /// A beat marker generated by music analysis; rendered as a compact tick
    /// and removable in bulk.
    case beat
}

/// A named marker placed on the timeline.
public struct Marker: Codable, Sendable, Equatable, Identifiable {
    /// The marker identifier.
    public var id: UUID

    /// The marker time in seconds.
    public var time: TimeInterval

    /// The user-visible marker name.
    public var name: String

    /// An optional hex color string for display.
    public var color: String?

    /// The marker kind. Legacy projects decode as `.standard`.
    public var kind: MarkerKind

    private enum CodingKeys: String, CodingKey {
        case id
        case time
        case name
        case color
        case kind
    }

    /// Creates a timeline marker.
    public init(
        id: UUID = UUID(),
        time: TimeInterval,
        name: String,
        color: String? = nil,
        kind: MarkerKind = .standard
    ) {
        self.id = id
        self.time = time
        self.name = name
        self.color = color
        self.kind = kind
    }

    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        time = try container.decode(TimeInterval.self, forKey: .time)
        name = try container.decode(String.self, forKey: .name)
        color = try container.decodeIfPresent(String.self, forKey: .color)
        kind = try container.decodeIfPresent(MarkerKind.self, forKey: .kind) ?? .standard
    }

    public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(time, forKey: .time)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(color, forKey: .color)
        if kind != .standard {
            try container.encode(kind, forKey: .kind)
        }
    }
}
