import CoreGraphics
import Foundation

/// Shared analytic ground truth for `moving_subject_320x240_2s_30fps.mp4`
/// (generated by scripts/make_fixtures.sh): a white 72x64 box on a black
/// 320x240 canvas starting at x=32, y=88 and moving +80px/s for 2s.
///
/// Used by both the IoU integration test and the T2-M performance suite so
/// the expected geometry lives in exactly one place.
enum MotionTrackingGroundTruth {
    /// Normalized (display-space, top-left origin) rect of the subject box at
    /// `timestamp`, clamped to the fixture's 2s span.
    static func expectedMovingSubjectRect(at timestamp: TimeInterval) -> CGRect {
        let width = 320.0
        let height = 240.0
        let boxWidth = 72.0
        let boxHeight = 64.0
        let startX = 32.0
        let y = 88.0
        let pixelsPerSecond = 80.0
        let clampedTimestamp = min(max(timestamp, 0), 2)
        return CGRect(
            x: (startX + pixelsPerSecond * clampedTimestamp) / width,
            y: y / height,
            width: boxWidth / width,
            height: boxHeight / height
        )
    }

    /// Intersection-over-union of two normalized rects.
    static func iou(_ lhs: CGRect, _ rhs: CGRect) -> Double {
        let intersection = lhs.intersection(rhs)
        guard !intersection.isNull, intersection.width > 0, intersection.height > 0 else {
            return 0
        }

        let intersectionArea = Double(intersection.width * intersection.height)
        let lhsArea = Double(lhs.width * lhs.height)
        let rhsArea = Double(rhs.width * rhs.height)
        let unionArea = lhsArea + rhsArea - intersectionArea
        guard unionArea > 0 else {
            return 0
        }

        return intersectionArea / unionArea
    }
}
