import CoreGraphics
import Foundation

/// Shared analytic ground truth for `moving_subject_320x240_2s_30fps.mp4`
/// (generated by scripts/make_fixtures.sh): a white 72x64 box on a black
/// 320x240 canvas starting at x=32, y=88 and moving +80px/s for 2s.
///
/// The occluded variant `moving_subject_occluded_320x240_3s_30fps.mp4` uses
/// the same box and trajectory over 3s with a mid-gray full-height wall at
/// canvas x=120..216 drawn on top (first contact t=0.2, fully occluded
/// t=[1.1, 1.4], fully emerged from t=2.3).
///
/// Used by both the IoU integration test and the T2-M performance suite so
/// the expected geometry lives in exactly one place.
enum MotionTrackingGroundTruth {
    /// Canvas geometry shared by both moving-subject fixtures.
    private static let canvasWidth = 320.0
    private static let canvasHeight = 240.0
    private static let boxWidth = 72.0
    private static let boxHeight = 64.0
    private static let startX = 32.0
    private static let boxY = 88.0
    private static let pixelsPerSecond = 80.0

    /// Wall (occluder) x-range in canvas pixels for the occluded fixture.
    static let occluderWallXRange = 120.0...216.0

    /// Normalized (display-space, top-left origin) rect of the subject box at
    /// `timestamp`, clamped to the fixture's span (2s plain, 3s occluded).
    static func expectedMovingSubjectRect(at timestamp: TimeInterval, duration: TimeInterval = 2) -> CGRect {
        let clampedTimestamp = min(max(timestamp, 0), duration)
        return CGRect(
            x: (startX + pixelsPerSecond * clampedTimestamp) / canvasWidth,
            y: boxY / canvasHeight,
            width: boxWidth / canvasWidth,
            height: boxHeight / canvasHeight
        )
    }

    /// Fraction of the subject box's width covered by the occluder wall at
    /// `timestamp` (0 = fully visible, 1 = fully hidden). The box's ground
    /// truth position is unchanged behind the wall — the wall only hides it.
    static func occlusionCoverageFraction(at timestamp: TimeInterval, duration: TimeInterval = 3) -> Double {
        let clamped = min(max(timestamp, 0), duration)
        let boxLeft = startX + pixelsPerSecond * clamped
        let boxRight = boxLeft + boxWidth
        let overlap = min(boxRight, occluderWallXRange.upperBound) - max(boxLeft, occluderWallXRange.lowerBound)
        guard overlap > 0 else { return 0 }
        return min(overlap / boxWidth, 1)
    }

    /// Intersection-over-union of two normalized rects.
    static func iou(_ lhs: CGRect, _ rhs: CGRect) -> Double {
        let intersection = lhs.intersection(rhs)
        guard !intersection.isNull, intersection.width > 0, intersection.height > 0 else {
            return 0
        }

        let intersectionArea = Double(intersection.width * intersection.height)
        let lhsArea = Double(lhs.width * lhs.height)
        let rhsArea = Double(rhs.width * rhs.height)
        let unionArea = lhsArea + rhsArea - intersectionArea
        guard unionArea > 0 else {
            return 0
        }

        return intersectionArea / unionArea
    }
}
